# Generated by Django 3.2 on 2022-05-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial number')),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', max_length=20, verbose_name='Model')),
                ('weight_limit', models.FloatField(default=500, verbose_name='Weight limit')),
                ('battery_capacity', models.FloatField(default=100, verbose_name='Weight limit')),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE', max_length=15, verbose_name='State')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('weight', models.FloatField(default=1, verbose_name='Weight')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='Code')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
