# Generated by Django 3.2 on 2022-05-22 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220521_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Battery capacity cannot be greater than 100.'), django.core.validators.MinValueValidator(limit_value=0, message='Battery capacity cannot be less than 0.')], verbose_name='Weight limit'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.FloatField(default=500, validators=[django.core.validators.MaxValueValidator(limit_value=500, message='Weight limit cannot be greater than 500.'), django.core.validators.MinValueValidator(limit_value=1, message='Weight limit cannot be less than 1.')], verbose_name='Weight limit'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid medication code.', regex='^([A-Z0-9]|-|_)+$')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='weight',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=500, message='Weight cannot be greater than 500.'), django.core.validators.MinValueValidator(limit_value=1, message='Weight cannot be less than 1.')], verbose_name='Weight'),
        ),
    ]
