# Generated by Django 3.2 on 2022-05-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220522_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('current_battery', models.FloatField(null=True, verbose_name='Current battery')),
                ('drone_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log_rel', to='base.drone', verbose_name='Drone')),
            ],
            options={
                'verbose_name': "Drone's status log",
            },
        ),
    ]
